const SCHEDULE = {
  "6/3":  { south: "55th Street",         north: "135th Street",          inlet: "OPEN" },
  "6/4":  { south: "53rd Street",          north: "133rd Street",          inlet: "OPEN" },
  "6/5":  { south: "51st Street",          north: "131st Street",          inlet: "OPEN" },
  "6/6":  { south: "49th Street",          north: "129th Street",          inlet: "Conditionally OPEN" },
  "6/7":  { south: "47th Street",          north: "127th Street",          inlet: "Conditionally OPEN" },
  "6/8":  { south: "45th Street",          north: "125th Street",          inlet: "OPEN" },
  "6/9":  { south: "43rd Street",          north: "123rd Street",          inlet: "OPEN" },
  "6/10": { south: "41st Street",          north: "121st Street",          inlet: "OPEN" },
  "6/11": { south: "39th Street",          north: "119th Street",          inlet: "OPEN" },
  "6/12": { south: "37th Street",          north: "Fountain Head (117)",   inlet: "OPEN" },
  "6/13": { south: "35th Street",          north: "High Point - North (114)", inlet: "Conditionally OPEN" },
  "6/14": { south: "33rd Street",          north: "Capri (111)",           inlet: "Conditionally OPEN" },
  "6/15": { south: "31st Street",          north: "Mid Atlantis (102)",    inlet: "OPEN" },
  "6/16": { south: "29th Street",          north: "Century I (99)",        inlet: "OPEN" },
  "6/17": { south: "27th Street",          north: "Flying Cloud (95)",     inlet: "OPEN" },
  "6/18": { south: "25th Street",          north: "93rd Street",           inlet: "OPEN" },
  "6/19": { south: "23rd Street",          north: "91st Street",           inlet: "OPEN" },
  "6/20": { south: "21st Street",          north: "89th Street",           inlet: "Conditionally OPEN" },
  "6/21": { south: "19th Street",          north: "87th Street",           inlet: "Conditionally OPEN" },
  "6/22": { south: "17th Street",          north: "85th Street",           inlet: "OPEN" },
  "6/23": { south: "15th Street",          north: "83rd Street",           inlet: "OPEN" },
  "6/24": { south: "13th Street",          north: "81st Street",           inlet: "OPEN" },
  "6/25": { south: "11th Street",          north: "79th Street",           inlet: "OPEN" },
  "6/26": { south: "9th Street",           north: "77th Street",           inlet: "OPEN" },
  "6/27": { south: "7th Street",           north: "75th Street",           inlet: "CLOSED" },
  "6/28": { south: "5th Street",           north: "73rd Street",           inlet: "CLOSED" },
  "6/29": { south: "3rd Street",           north: "71st Street",           inlet: "OPEN" },
  "6/30": { south: "1st Street",           north: "69th Street",           inlet: "OPEN" },
  "7/1":  { south: "Caroline Street",      north: "67th Street",           inlet: "OPEN" },
  "7/2":  { south: "66th Street",          north: "146th Street",          inlet: "OPEN" },
  "7/3":  { south: "64th Street",          north: "144th Street",          inlet: "OPEN" },
  "7/4":  { south: "62nd Street",          north: "142nd Street",          inlet: "CLOSED" },
  "7/5":  { south: "60th Street",          north: "140th Street",          inlet: "CLOSED" },
  "7/6":  { south: "58th Street",          north: "138th Street",          inlet: "OPEN" },
  "7/7":  { south: "56th Street",          north: "136th Street",          inlet: "OPEN" },
  "7/8":  { south: "54th Street",          north: "134th Street",          inlet: "OPEN" },
  "7/9":  { south: "52nd Street",          north: "132nd Street",          inlet: "OPEN" },
  "7/10": { south: "50th Street",          north: "130th Street",          inlet: "OPEN" },
  "7/11": { south: "48th Street",          north: "128th Street",          inlet: "CLOSED" },
  "7/12": { south: "46th Street",          north: "126th Street",          inlet: "CLOSED" },
  "7/13": { south: "44th Street",          north: "124th Street",          inlet: "OPEN" },
  "7/14": { south: "42nd Street",          north: "122nd Street",          inlet: "OPEN" },
  "7/15": { south: "40th Street",          north: "120th Street",          inlet: "OPEN" },
  "7/16": { south: "38th Street",          north: "Carousel (118)",        inlet: "OPEN" },
  "7/17": { south: "36th Street",          north: "Sea Watch (116)",       inlet: "OPEN" },
  "7/18": { south: "34th Street",          north: "Rainbow (112)",         inlet: "CLOSED" },
  "7/19": { south: "32nd Street",          north: "Quay (108)",            inlet: "CLOSED" },
  "7/20": { south: "30th Street",          north: "Marigot Beach (101)",   inlet: "OPEN" },
  "7/21": { south: "28th Street",          north: "Mid Plaza (97)",        inlet: "OPEN" },
  "7/22": { south: "26th Street",          north: "94th Street",           inlet: "OPEN" },
  "7/23": { south: "24th Street",          north: "92nd Street",           inlet: "OPEN" },
  "7/24": { south: "22nd Street",          north: "90th Street",           inlet: "OPEN" },
  "7/25": { south: "20th Street",          north: "88th Street",           inlet: "CLOSED" },
  "7/26": { south: "18th Street",          north: "86th Street",           inlet: "CLOSED" },
  "7/27": { south: "16th Street",          north: "84th Street",           inlet: "OPEN" },
  "7/28": { south: "14th Street",          north: "82nd Street",           inlet: "OPEN" },
  "7/29": { south: "12th Street",          north: "80th Street",           inlet: "OPEN" },
  "7/30": { south: "10th Street",          north: "78th Street",           inlet: "OPEN" },
  "7/31": { south: "8th Street",           north: "76th Street",           inlet: "OPEN" },
  "8/1":  { south: "6th Street",           north: "74th Street",           inlet: "CLOSED" },
  "8/2":  { south: "4th Street",           north: "72nd Street",           inlet: "CLOSED" },
  "8/3":  { south: "2nd Street",           north: "70th Street",           inlet: "OPEN" },
  "8/4":  { south: "North Division St",    north: "68th Street",           inlet: "OPEN" },
  "8/5":  { south: "65th Street",          north: "145th Street",          inlet: "OPEN" },
  "8/6":  { south: "63rd Street",          north: "143rd Street",          inlet: "OPEN" },
  "8/7":  { south: "61st Street",          north: "141st Street",          inlet: "OPEN" },
  "8/8":  { south: "59th Street",          north: "139th Street",          inlet: "CLOSED" },
  "8/9":  { south: "57th Street",          north: "137th Street",          inlet: "CLOSED" },
  "8/10": { south: "55th Street",          north: "135th Street",          inlet: "OPEN" },
  "8/11": { south: "53rd Street",          north: "133rd Street",          inlet: "OPEN" },
  "8/12": { south: "51st Street",          north: "131st Street",          inlet: "OPEN" },
  "8/13": { south: "49th Street",          north: "129th Street",          inlet: "OPEN" },
  "8/14": { south: "47th Street",          north: "127th Street",          inlet: "OPEN" },
  "8/15": { south: "45th Street",          north: "125th Street",          inlet: "CLOSED" },
  "8/16": { south: "43rd Street",          north: "123rd Street",          inlet: "CLOSED" },
  "8/17": { south: "41st Street",          north: "121st Street",          inlet: "OPEN" },
  "8/18": { south: "39th Street",          north: "119th Street",          inlet: "OPEN" },
  "8/19": { south: "37th Street",          north: "Fountain Head (117)",   inlet: "OPEN" },
  "8/20": { south: "35th Street",          north: "High Point - North (114)", inlet: "OPEN" },
  "8/21": { south: "33rd Street",          north: "Capri (111)",           inlet: "OPEN" },
  "8/22": { south: "31st Street",          north: "Mid Atlantis (102)",    inlet: "Conditionally OPEN" },
  "8/23": { south: "29th Street",          north: "Century I (99)",        inlet: "Conditionally OPEN" },
  "8/24": { south: "27th Street",          north: "Flying Cloud (95)",     inlet: "OPEN" },
  "8/25": { south: "25th Street",          north: "93rd Street",           inlet: "OPEN" },
  "8/26": { south: "23rd Street",          north: "91st Street",           inlet: "OPEN" },
  "8/27": { south: "21st Street",          north: "89th Street",           inlet: "OPEN" },
  "8/28": { south: "19th Street",          north: "87th Street",           inlet: "OPEN" },
  "8/29": { south: "17th Street",          north: "85th Street",           inlet: "Conditionally OPEN" },
  "8/30": { south: "15th Street",          north: "83rd Street",           inlet: "Conditionally OPEN" },
  "8/31": { south: "13th Street",          north: "81st Street",           inlet: "OPEN" },
  "9/1":  { south: "11th Street",          north: "79th Street",           inlet: "OPEN" },
  "9/2":  { south: "9th Street",           north: "77th Street",           inlet: "OPEN" },
  "9/3":  { south: "7th Street",           north: "75th Street",           inlet: "OPEN" },
  "9/4":  { south: "5th Street",           north: "73rd Street",           inlet: "OPEN" },
  "9/5":  { south: "3rd Street",           north: "71st Street",           inlet: "Conditionally OPEN" },
  "9/6":  { south: "1st Street",           north: "69th Street",           inlet: "Conditionally OPEN" },
  "9/7":  { south: "Caroline Street",      north: "67th Street",           inlet: "Conditionally OPEN" },
  "9/8":  { south: "66th Street",          north: "146th Street",          inlet: "OPEN" },
  "9/9":  { south: "64th Street",          north: "144th Street",          inlet: "OPEN" },
  "9/10": { south: "62nd Street",          north: "142nd Street",          inlet: "OPEN" },
  "9/11": { south: "60th Street",          north: "140th Street",          inlet: "OPEN" },
  "9/12": { south: "58th Street",          north: "138th Street",          inlet: "Conditionally OPEN" },
  "9/13": { south: "56th Street",          north: "136th Street",          inlet: "Conditionally OPEN" },
  "9/14": { south: "54th Street",          north: "134th Street",          inlet: "OPEN" },
  "9/15": { south: "52nd Street",          north: "132nd Street",          inlet: "OPEN" },
  "9/16": { south: "50th Street",          north: "130th Street",          inlet: "OPEN" },
  "9/17": { south: "48th Street",          north: "128th Street",          inlet: "OPEN" },
  "9/18": { south: "46th Street",          north: "126th Street",          inlet: "OPEN" },
  "9/19": { south: "44th Street",          north: "124th Street",          inlet: "Conditionally OPEN" },
  "9/20": { south: "42nd Street",          north: "122nd Street",          inlet: "Conditionally OPEN" },
  "9/21": { south: "40th Street",          north: "120th Street",          inlet: "OPEN" },
  "9/22": { south: "38th Street",          north: "Carousel (118)",        inlet: "OPEN" },
  "9/23": { south: "36th Street",          north: "Sea Watch (116)",       inlet: "OPEN" },
  "9/24": { south: "34th Street",          north: "Rainbow (112)",         inlet: "OPEN" },
  "9/25": { south: "32nd Street",          north: "Quay (108)",            inlet: "OPEN" },
  "9/26": { south: "30th Street",          north: "Marigot Beach (101)",   inlet: "Conditionally OPEN" },
  "9/27": { south: "28th Street",          north: "Mid Plaza (97)",        inlet: "Conditionally OPEN" },
  "9/28": { south: "26th Street",          north: "94th Street",           inlet: "OPEN" },
  "9/29": { south: "24th Street",          north: "92nd Street",           inlet: "OPEN" },
  "9/30": { south: "22nd Street",          north: "90th Street",           inlet: "OPEN" },
};

function getTodaysSurfBeaches() {
  const now = new Date(new Date().toLocaleString("en-US", { timeZone: "America/New_York" }));
  const key = `${now.getMonth() + 1}/${now.getDate()}`;
  return SCHEDULE[key] || { south: null, north: null, inlet: null };
}

module.exports = { getTodaysSurfBeaches };
